import java.awt.Color;
import java.awt.Graphics2D;
import java.util.Random;

public class LandingZone 
{
	private DataManager Data;
	protected int width;		//Width of the landing pad
	private int height;			//Height of the landing pad
	protected int xPosition;	//generated by the random number generator
	private int yPosition;		//always on the surface of the planet
	private Random random;		//Randomly generated xPosition
	
	public LandingZone(DataManager DataIn)
	{
		Data = DataIn;
		random = new Random();
		xPosition = (random.nextInt((int)(Data.WindowWidth * .75)) + 1);
	}
	
	public void draw(Graphics2D g, int heightIn)
	{
		yPosition = heightIn;
		width = (int)(Data.WindowWidth * .1);
		height = (int)(Data.WindowHeight * .05);
		g.setColor(Color.RED);
		g.fillOval(xPosition, yPosition, width, height);
	}
}
